### ISSUE TITLE
为什么您上传的代码中没有mamba模组

### ISSUE THREAD

**Issue by loveciel** [wzhwzhwzh0921/S-D-Mamba#12]
Traceback (most recent call last):
  File "E:\模型\S-D-Mamba-main\S-D-Mamba-main\run.py", line 3, in <module>
    from experiments.exp_long_term_forecasting import Exp_Long_Term_Forecast
  File "E:\模型\S-D-Mamba-main\S-D-Mamba-main\experiments\exp_long_term_forecasting.py", line 4, in <module>
    from experiments.exp_basic import Exp_Basic
  File "E:\模型\S-D-Mamba-main\S-D-Mamba-main\experiments\exp_basic.py", line 3, in <module>
    from model import Transformer, Informer, Reformer, Flowformer, Flashformer, \
  File "E:\模型\S-D-Mamba-main\S-D-Mamba-main\model\Transformer.py", line 6, in <module>
    from layers.Embed import DataEmbedding
  File "E:\模型\S-D-Mamba-main\S-D-Mamba-main\layers\Embed.py", line 5, in <module>
    from mamba_ssm import Mamba
ModuleNotFoundError: No module named 'mamba_ssm'

**Comment by wzhwzhwzh0921** [comment]
Hi~ Thanks for testing the code. Mamba-ssm needs to be installed. You can try 'pip install mamba-ssm' or check other methods in the repository of Mamba.

**Comment by loveciel** [comment]
> Hi~ Thanks for testing the code. Mamba-ssm needs to be installed. You can try 'pip install mamba-ssm' or check other methods in the repository of Mamba.

我尝试了pip和conda都不能完成下载人物

**Comment by wzhwzhwzh0921** [comment]
You can refer to [Mamba](https://github.com/state-spaces/mamba)

**Comment by ZhangYiqun018** [comment]
> > Hi~ Thanks for testing the code. Mamba-ssm needs to be installed. You can try 'pip install mamba-ssm' or check other methods in the repository of Mamba.
> 
> 我尝试了pip和conda都不能完成下载人物

你是不是开代理下载了
