### ISSUE TITLE
当我使用别的数据进行训练时，有问题

### ISSUE THREAD

**Issue by 2326261098** [wzhwzhwzh0921/S-D-Mamba#27]
**这是报错信息**
root@autodl-container-40c34f99e4-9444b1eb:~/autodl-tmp/S-D-Mamba# bash ./scripts/multivariate_forecasting/wind/wind.sh
Args in experiment:
Namespace(is_training=1, model_id='wind_data_96_96', model='S_Mamba', data='custom', root_path='./dataset/wind_data/', data_path='wind_data.csv', features='M', target='OT', freq='h', checkpoints='./checkpoints/', seq_len=96, label_len=48, pred_len=96, enc_in=14, dec_in=14, c_out=14, d_model=512, n_heads=8, e_layers=3, d_layers=1, d_ff=512, moving_avg=25, factor=1, distil=True, dropout=0.1, embed='timeF', activation='gelu', output_attention=False, do_predict=False, num_workers=10, itr=1, train_epochs=5, batch_size=32, patience=3, learning_rate=0.001, des='Exp', loss='MSE', lradj='type1', use_amp=False, use_gpu=True, gpu=0, use_multi_gpu=False, devices='0,1,2,3', exp_name='MTSF', channel_independence=False, inverse=False, class_strategy='projection', target_root_path='./data/electricity/', target_data_path='electricity.csv', efficient_training=False, use_norm=True, partial_start_index=0, d_state=2)
Use GPU: cuda:0
>>>>>>>start training : wind_data_96_96_S_Mamba_custom_M_ft96_sl48_ll96_pl512_dm8_nh3_el1_dl512_df1_fctimeF_ebTrue_dtExp_projection_0>>>>>>>>>>>>>>>>>>>>>>>>>>
train 509
val 5
test 105
Epoch: 1 cost time: 1.8727619647979736
Epoch: 1, Steps: 15 | Train Loss: 1.1316504 Vali Loss: nan Test Loss: 3.7549150
Validation loss decreased (inf --> nan).  Saving model ...
Updating learning rate to 0.001
Epoch: 2 cost time: 0.6668744087219238
Epoch: 2, Steps: 15 | Train Loss: 0.8750212 Vali Loss: nan Test Loss: 3.8634474
Validation loss decreased (nan --> nan).  Saving model ...
Updating learning rate to 0.0005
Epoch: 3 cost time: 0.5717065334320068
Epoch: 3, Steps: 15 | Train Loss: 0.6897496 Vali Loss: nan Test Loss: 3.9581139
Validation loss decreased (nan --> nan).  Saving model ...
Updating learning rate to 0.00025
Epoch: 4 cost time: 0.6605472564697266
Epoch: 4, Steps: 15 | Train Loss: 0.5578691 Vali Loss: nan Test Loss: 4.0534134
Validation loss decreased (nan --> nan).  Saving model ...
Updating learning rate to 0.000125
Epoch: 5 cost time: 0.8430545330047607
Epoch: 5, Steps: 15 | Train Loss: 0.5024049 Vali Loss: nan Test Loss: 4.0625038
Validation loss decreased (nan --> nan).  Saving model ...
Updating learning rate to 6.25e-05
>>>>>>>testing : wind_data_96_96_S_Mamba_custom_M_ft96_sl48_ll96_pl512_dm8_nh3_el1_dl512_df1_fctimeF_ebTrue_dtExp_projection_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test 105
test shape: (105, 1, 96, 14) (105, 1, 96, 14)
test shape: (105, 96, 14) (105, 96, 14)
mse:4.062503337860107, mae:1.486275553703308
Args in experiment:
Namespace(is_training=1, model_id='wind_data_96_192', model='S_Mamba', data='custom', root_path='./dataset/wind_data/', data_path='wind_data.csv', features='M', target='OT', freq='h', checkpoints='./checkpoints/', seq_len=96, label_len=48, pred_len=192, enc_in=14, dec_in=14, c_out=14, d_model=512, n_heads=8, e_layers=3, d_layers=1, d_ff=512, moving_avg=25, factor=1, distil=True, dropout=0.1, embed='timeF', activation='gelu', output_attention=False, do_predict=False, num_workers=10, itr=1, train_epochs=5, batch_size=32, patience=3, learning_rate=0.001, des='Exp', loss='MSE', lradj='type1', use_amp=False, use_gpu=True, gpu=0, use_multi_gpu=False, devices='0,1,2,3', exp_name='MTSF', channel_independence=False, inverse=False, class_strategy='projection', target_root_path='./data/electricity/', target_data_path='electricity.csv', efficient_training=False, use_norm=True, partial_start_index=0, d_state=2)
Use GPU: cuda:0
>>>>>>>start training : wind_data_96_192_S_Mamba_custom_M_ft96_sl48_ll192_pl512_dm8_nh3_el1_dl512_df1_fctimeF_ebTrue_dtExp_projection_0>>>>>>>>>>>>>>>>>>>>>>>>>>
train 413
Traceback (most recent call last):
  File "/root/autodl-tmp/S-D-Mamba/run.py", line 135, in <module>
    exp.train(setting)
  File "/root/autodl-tmp/S-D-Mamba/experiments/exp_long_term_forecasting.py", line 87, in train
    vali_data, vali_loader = self._get_data(flag='val')
  File "/root/autodl-tmp/S-D-Mamba/experiments/exp_long_term_forecasting.py", line 30, in _get_data
    data_set, data_loader = data_provider(self.args, flag)
  File "/root/autodl-tmp/S-D-Mamba/data_provider/data_factory.py", line 47, in data_provider
    print(flag, len(data_set))
ValueError: __len__() should return >= 0
Args in experiment:
Namespace(is_training=1, model_id='wind_data_96_336', model='S_Mamba', data='custom', root_path='./dataset/wind_data/', data_path='wind_data.csv', features='M', target='OT', freq='h', checkpoints='./checkpoints/', seq_len=96, label_len=48, pred_len=336, enc_in=14, dec_in=14, c_out=14, d_model=512, n_heads=8, e_layers=3, d_layers=1, d_ff=512, moving_avg=25, factor=1, distil=True, dropout=0.1, embed='timeF', activation='gelu', output_attention=False, do_predict=False, num_workers=10, itr=1, train_epochs=1, batch_size=32, patience=3, learning_rate=0.001, des='Exp', loss='MSE', lradj='type1', use_amp=False, use_gpu=True, gpu=0, use_multi_gpu=False, devices='0,1,2,3', exp_name='MTSF', channel_independence=False, inverse=False, class_strategy='projection', target_root_path='./data/electricity/', target_data_path='electricity.csv', efficient_training=False, use_norm=True, partial_start_index=0, d_state=2)
Use GPU: cuda:0
>>>>>>>start training : wind_data_96_336_S_Mamba_custom_M_ft96_sl48_ll336_pl512_dm8_nh3_el1_dl512_df1_fctimeF_ebTrue_dtExp_projection_0>>>>>>>>>>>>>>>>>>>>>>>>>>
train 269
Traceback (most recent call last):
  File "/root/autodl-tmp/S-D-Mamba/run.py", line 135, in <module>
    exp.train(setting)
  File "/root/autodl-tmp/S-D-Mamba/experiments/exp_long_term_forecasting.py", line 87, in train
    vali_data, vali_loader = self._get_data(flag='val')
  File "/root/autodl-tmp/S-D-Mamba/experiments/exp_long_term_forecasting.py", line 30, in _get_data
    data_set, data_loader = data_provider(self.args, flag)
  File "/root/autodl-tmp/S-D-Mamba/data_provider/data_factory.py", line 47, in data_provider
    print(flag, len(data_set))
ValueError: __len__() should return >= 0
Args in experiment:
Namespace(is_training=1, model_id='wind_data_96_720', model='S_Mamba', data='custom', root_path='./dataset/wind_data/', data_path='wind_data.csv', features='M', target='OT', freq='h', checkpoints='./checkpoints/', seq_len=96, label_len=48, pred_len=720, enc_in=14, dec_in=14, c_out=14, d_model=512, n_heads=8, e_layers=3, d_layers=1, d_ff=512, moving_avg=25, factor=1, distil=True, dropout=0.1, embed='timeF', activation='gelu', output_attention=False, do_predict=False, num_workers=10, itr=1, train_epochs=5, batch_size=32, patience=3, learning_rate=0.001, des='Exp', loss='MSE', lradj='type1', use_amp=False, use_gpu=True, gpu=0, use_multi_gpu=False, devices='0,1,2,3', exp_name='MTSF', channel_independence=False, inverse=False, class_strategy='projection', target_root_path='./data/electricity/', target_data_path='electricity.csv', efficient_training=False, use_norm=True, partial_start_index=0, d_state=2)
Use GPU: cuda:0
>>>>>>>start training : wind_data_96_720_S_Mamba_custom_M_ft96_sl48_ll720_pl512_dm8_nh3_el1_dl512_df1_fctimeF_ebTrue_dtExp_projection_0>>>>>>>>>>>>>>>>>>>>>>>>>>
Traceback (most recent call last):
  File "/root/autodl-tmp/S-D-Mamba/run.py", line 135, in <module>
    exp.train(setting)
  File "/root/autodl-tmp/S-D-Mamba/experiments/exp_long_term_forecasting.py", line 86, in train
    train_data, train_loader = self._get_data(flag='train')
  File "/root/autodl-tmp/S-D-Mamba/experiments/exp_long_term_forecasting.py", line 30, in _get_data
    data_set, data_loader = data_provider(self.args, flag)
  File "/root/autodl-tmp/S-D-Mamba/data_provider/data_factory.py", line 47, in data_provider
    print(flag, len(data_set))
ValueError: __len__() should return >= 0

以下是相关命令
export CUDA_VISIBLE_DEVICES=0

model_name=S_Mamba

python -u run.py \
  --is_training 1 \
  --root_path ./dataset/wind_data/ \
  --data_path wind_data.csv \
  --model_id wind_data_96_96 \
  --model $model_name \
  --data custom \
  --features M \
  --seq_len 96 \
  --pred_len 96 \
  --e_layers 3 \
  --enc_in 14 \
  --dec_in 14 \
  --c_out 14 \
  --des 'Exp' \
  --d_model 512\
  --learning_rate 0.001 \
  --train_epochs 5\
  --d_state 2 \
  --d_ff 512\
  --itr 1

python -u run.py \
  --is_training 1 \
  --root_path ./dataset/wind_data/ \
  --data_path wind_data.csv \
  --model_id wind_data_96_192 \
  --model $model_name \
  --data custom \
  --features M \
  --seq_len 96 \
  --pred_len 192 \
  --e_layers 3 \
  --enc_in 14 \
  --dec_in 14 \
  --c_out 14 \
  --des 'Exp' \
  --learning_rate 0.001 \
  --train_epochs 5\
  --d_model 512\
  --d_state 2 \
  --d_ff 512\
  --itr 1

python -u run.py \
  --is_training 1 \
  --root_path ./dataset/wind_data/ \
  --data_path wind_data.csv \
  --model_id wind_data_96_336 \
  --model $model_name \
  --data custom \
  --features M \
  --seq_len 96 \
  --pred_len 336 \
  --e_layers 3 \
  --enc_in 14 \
  --dec_in 14 \
  --c_out 14 \
  --des 'Exp' \
  --learning_rate 0.001 \
  --train_epochs 1\
  --d_model 512\
  --d_state 2 \
  --d_ff 512\
  --itr 1

python -u run.py \
  --is_training 1 \
  --root_path ./dataset/wind_data/ \
  --data_path wind_data.csv \
  --model_id wind_data_96_720 \
  --model $model_name \
  --data custom \
  --features M \
  --seq_len 96 \
  --pred_len 720 \
  --e_layers 3 \
  --enc_in 14 \
  --dec_in 14 \
  --c_out 14 \
  --des 'Exp' \
  --learning_rate 0.001 \
  --train_epochs 5\
  --d_model 512\
  --d_state 2 \
  --d_ff 512\
  --itr 1

**Comment by wzhwzhwzh0921** [comment]
检查一下数据处理那里，所有的数据都被处理成相同格式，确保格式对齐
